@Restaurants.API_HostAddress = https://localhost:7186


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1005

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "hagoga",
  "Description": "Egyptian Authentic food",
  "Category": "Egyptian",
  "HasDelivery": true,
  "ContactEmail": "ContactUs@hagoga.com",
  "ContactNumber": "0101111111111",
  "City": "Cairo",
  "Street": "Madinet Nasr",
  "PostalCode": "97-726"

}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1004

###
