@Restaurants.API_HostAddress = https://localhost:7186
@token = CfDJ8BO101DFH29DpooweU0H4KX6GnMgGJEBn43ym2EOMiqqE-wYuW7RmD6LcfNU35_WR9i5opsSb93zDfvrFuiI-igQtkCJLxYJ-Y7CrROM6qHnTAqYNAn2H1frOrBmlQOeISIvurNSLUzvbmYMK34BxXl1d9gxL1Lv7ZRe4xBj_Hx6nIdrZt8cexpujYA_TS2dD_0w4MKV_r_r90i60Q8xHqq1wP8YUyTSdHDkKbFJHW0VSf55CbutNzsaE2J0PB0uO9SvqnS7n0_Kolt-DeFIzDm6Fp2awdkeZeoU3BlJwQrb_1xp8VSUqKYWy8ncxYLaH7n22kHB8QZfQB08yGIuNlRC-VmpeeX04pm7aM_XDXmqFI5Uk8hQgUfL197efVaY5rdLjbafYjEJ75VrWUjC8XwtCIq8EbQPBxBAeBwNZ_otjRc1YajxwUR5tCKeafoeRYaz-bLcNIPG_RE9l9VWDdr-XiuuzKxK7pHNDggZitdXB0R5VRJ8GHqzwN0O1aVyud4lQHwGkeyyWn7Jcpj3xkssNUIybNHothkq6u3FYnIPSvAzrlkomUb-qofySNXY4YLaWicc8UWhiJ7DPEdDpVN05K7DGLx0j9S6GVdtQDYsBlmBtZT5Qm4YeeBV0n1q4mm1t4Gsj76oDtpAclGWKBWJS-l_tz54SnvzKy5LzwCrup824DJhRbdKSfJhKugmoOiGlKW-eUXvTWyHQucgPgM

GET {{Restaurants.API_HostAddress}}/api/restaurants?SearchPhrase=wiza&PageSize=5&PageNumber=3

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1006
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Amigos",
  "Description": "Mexican food",
  "Category": "Mexican",
  "HasDelivery": true,
  "ContactEmail": "ContactUs@amigos.com",
  "ContactNumber": "01011111121211",
  "City": "Cairo",
  "Street": "Mokattam",
  "PostalCode": "97-726"

}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1004

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1006
Content-Type: application/json

{
  "Name": "Amigos",
  "Description": "Mexican food in Egypt",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1006/dishes
Content-Type: application/json

{
  "Name": "Tacos",
  "Description": "Delicious beef Tacos",
  "Price": 179,
  "KiloCalories": 1400
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1006/dishes/4

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1006/dishes

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1006/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password_1"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password_1"
}

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json

{
  //UpdateUserDetailsCommand
}

###
